- registration_portal/package-lock.json
- registration_portal/package.json
- registration_portal/public/index.html
- registration_portal/src/App.js
- registration_portal/src/Assests/Images/rightIcon.svg
- registration_portal/src/Components/Home/Home.css
- registration_portal/src/Components/Registration/NewRegistration.css
- registration_portal/src/Components/Registration/NewRegistration.js
integrated capture feature in newRegistration. Integration  not complete
> integrated capture feature in newRegistration. Integration  not complete

- registration_portal/src/Components/Home/Home.js
- registration_portal/src/Components/Registration/RegisterPatientDetail.css
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
Updated CSS for newRegistrationDetails
> Updated CSS for newRegistrationDetails

- registration_portal/src/App.js
- registration_portal/src/Components/Home/Home.js
- registration_portal/src/Components/Registration/NewRegisterBookConsultation.js
- registration_portal/src/Components/Registration/NewRegistrationAadhar.js
- registration_portal/src/Components/Registration/RegisterPatientDetail.css
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
New RegistrationPage on Progress
> New RegistrationPage on Progress

- registration_portal/src/Components/Registration/RegisterPatientDetail.css
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
integrated Post API(for Aadhar Data) in NewRegistrationDetailJS and CSS
> integrated Post API(for Aadhar Data) in NewRegistrationDetailJS and CSS

- registration_portal/src/Components/Home/Home.js
- registration_portal/src/Components/Registration/NewRegistration.js
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
Updated Photo Capture Scenario while new registration.
> Updated Photo Capture Scenario while new registration.

- registration_portal/src/Components/Navbar/PatientCard.js
- registration_portal/src/Components/Registration/NewRegisterBookConsultation.css
- registration_portal/src/Components/Registration/NewRegisterBookConsultation.js
- registration_portal/src/Components/Registration/NewRegistration.js
Added Search functionality in newRegisterBookConsultation
> Added Search functionality in newRegisterBookConsultation

- registration_portal/src/Components/Registration/NewRegisterBookConsultation.js
changes in DoctorSlots(employeeId acc to doctorId working fine)
> changes in DoctorSlots(employeeId acc to doctorId working fine)

- registration_portal/src/Components/BookAppointment/Billing/Billing.js
- registration_portal/src/Components/BookAppointment/BookAppointment.js
- registration_portal/src/Components/BookAppointment/LabReport/LabReport.css
- registration_portal/src/Components/BookAppointment/LabReport/LabReport.js
Lab Reports and Billing Tab Done
> Lab Reports and Billing Tab Done

- registration_portal/src/Components/BookAppointment/BookAppointment.js
- registration_portal/src/Components/Registration/NewRegisterBookConsultation.js
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
POST API (HIMS)done for NewRegisterBookConsultation
> POST API (HIMS)done for NewRegisterBookConsultation

- registration_portal/src/Components/HospitalDetail/HospitalDetails.js
reverting clickable Link in HospitalDetails
> reverting clickable Link in HospitalDetails

- registration_portal/src/Components/BookAppointment/AllPatient.css
- registration_portal/src/Components/BookAppointment/AllPatients.js
- registration_portal/src/Components/BookAppointment/Billing/Billing.js
- registration_portal/src/Components/BookAppointment/BookAppointment.js
- registration_portal/src/Components/BookAppointment/BookAppointmentLanding.js
- registration_portal/src/Components/BookAppointment/BookConsultation/BookConsultation.js
- registration_portal/src/Components/BookAppointment/LabReport/LabReport.js
- registration_portal/src/Components/BookAppointment/OPD_CheckIn/OpdCheckin.js
- registration_portal/src/Components/Navbar/Navbar.js
- registration_portal/src/Components/Registration/NewRegisterBookConsultation.js
- registration_portal/src/Components/Registration/NewRegistration.js
- registration_portal/src/Components/Registration/NewRegistrationAadhar.js
Added condition for Back,home Button in all Pages
> Added condition for Back,home Button in all Pages

- registration_portal/src/Components/BookAppointment/BookAppointment.js
- registration_portal/src/Components/Home/Home.js
- registration_portal/src/Components/Navbar/Navbar.js
> Close Session Changes

- registration_portal/src/Components/BookAppointment/BookConsultation/BookConsultation.js
- registration_portal/src/Components/Home/Home.js
- registration_portal/src/Components/Registration/NewRegisterBookConsultation.js
removed LocalStorage on Redirection to Home
> removed LocalStorage on Redirection to Home

- registration_portal/src/Components/Faqs/Faqs.js
- registration_portal/src/Components/HospitalDetail/HospitalDetails.js
- registration_portal/src/Components/Navbar/Navbar.js
updates in FAQ and HospitalDetail
> updates in FAQ and HospitalDetail

- registration_portal/src/Components/BookAppointment/AllPatients.js
- registration_portal/src/Components/BookAppointment/BookConsultation/BookConsultation.js
- registration_portal/src/Components/Home/SuccessConfirmation.js
- registration_portal/src/Components/Navbar/Navbar.js
- registration_portal/src/Components/Navbar/PatientCard.js
- registration_portal/src/Components/Registration/NewRegisterBookConsultation.js
- registration_portal/src/Components/Registration/NewRegistrationAadhar.js
API Integration Completed for BookConsultationSuccessConfirmation
> API Integration Completed for BookConsultationSuccessConfirmation

- registration_portal/src/Components/Navbar/Navbar.js
clearing LocalStorage On Close Session
> clearing LocalStorage On Close Session

- registration_portal/src/Components/BookAppointment/BookConsultation/BookConsultation.js
- registration_portal/src/Components/BookAppointment/OPD_CheckIn/OpdCheckin.js
> pushing changes

- registration_portal/src/Components/BookAppointment/BookAppointment.js
- registration_portal/src/Components/Registration/RegisterPatientDetail.css
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
Added Suggestion Box in locality
> Added Suggestion Box in locality

- registration_portal/.env
- registration_portal/src/Components/Admin/AdminPage.js
- registration_portal/src/Components/BookAppointment/BookAppointment.css
- registration_portal/src/Components/BookAppointment/BookAppointment.js
- registration_portal/src/Components/Registration/NewRegistrationAadhar.css
- registration_portal/src/Components/Registration/NewRegistrationAadhar.js
Minor Changes(Added KeyPress in mobile Number and AAdhar Validation)
> Minor Changes(Added KeyPress in mobile Number and AAdhar Validation)

- registration_portal/src/Components/Admin/AdminPage.js
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
updated gender Comparison for aadharGender in RegisterPatientDetail
> updated gender Comparison for aadharGender in RegisterPatientDetail

- registration_portal/src/Components/BookAppointment/BookConsultation/BookConsultation.js
- registration_portal/src/Components/Registration/NewRegistration.js
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
> PinCode Suggestion Inprogress

- registration_portal/src/Components/BookAppointment/AllPatients.js
- registration_portal/src/Components/BookAppointment/OPD_CheckIn/OpdCheckin.js
OPD check-IN changes(show future appointment)
> OPD check-IN changes(show future appointment)

- registration_portal/src/Components/Navbar/PatientCard.js
Updated lastname null check in PatientCard
> Updated lastname null check in PatientCard

- registration_portal/src/App.js
- registration_portal/src/Components/Admin/AdminPage.css
- registration_portal/src/Components/Admin/AdminPage.js
- registration_portal/src/Components/AuthContext.js
- registration_portal/src/Components/BookAppointment/AllPatients.js
- registration_portal/src/Components/BookAppointment/Billing/Billing.js
- registration_portal/src/Components/BookAppointment/BookAppointment.js
- registration_portal/src/Components/BookAppointment/BookConsultation/BookConsultation.js
- registration_portal/src/Components/BookAppointment/LabReport/LabReport.js
- registration_portal/src/Components/BookAppointment/OPD_CheckIn/OpdCheckin.js
- registration_portal/src/Components/Faqs/Faqs.js
- registration_portal/src/Components/Home/CloseSession.js
- registration_portal/src/Components/Home/SuccessConfirmation.js
- registration_portal/src/Components/HospitalDetail/HospitalDetails.js
- registration_portal/src/Components/Navbar/Navbar.js
- registration_portal/src/Components/Registration/NewRegisterBookConsultation.js
- registration_portal/src/Components/Registration/NewRegistrationAadhar.js
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
Added Token Based Authentication In KIOSK
> Added Token Based Authentication In KIOSK

- registration_portal/src/Components/BookAppointment/Billing/Billing.js
Added token in print billing function
> Added token in print billing function

- registration_portal/src/Components/BookAppointment/BookConsultation/BookConsultation.js
- registration_portal/src/Components/Registration/RegisterPatientDetail.js
added isAlreadyRegistered=True in bookConsultation
> added isAlreadyRegistered=True in bookConsultation

- registration_portal/src/Components/Registration/RegisterPatientDetail.js
> Develop sync to kiosk 1.0

- registration_portal/.env
Updated context path from soul to kiosk
> Updated context path from soul to kiosk
